/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WindEstimationPanel.java
 *
 * Created on Sep 10, 2010, 8:59:18 AM
 */

package edu.jhuapl.nstd.swarm;

import edu.jhuapl.nstd.piccolo.Pic_Telemetry;
import edu.jhuapl.nstd.swarm.belief.BeliefManager;
import edu.jhuapl.nstd.swarm.belief.BeliefManagerImpl;
import edu.jhuapl.nstd.swarm.belief.PiccoloTelemetryBelief;
import edu.jhuapl.nstd.swarm.comms.BeliefManagerClient;
import edu.jhuapl.nstd.swarm.display.BearingDial;
import edu.jhuapl.nstd.swarm.util.MonitorClient;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.Formatter;

/**
 *
 * @author humphjc1
 */
public class WindEstimationPanel extends javax.swing.JDialog implements Updateable {

    BeliefManager belMgr;
    Thread thread;
    BearingDial picDial;
    BearingDial estDial;
    PiccoloTelemetryBelief lastTelem;


    /**
     * Buffered writer object to save flat files to
     */
    private BufferedWriter m_LogFileWriter = null;

    /**
     * Flat file object
     */
    private File m_LogFile = null;

    /**
     * File size limit for flat files
     */
    private int MAX_LOG_FILE_BYTES = 10000000;

    /**
     * Counter for filenames to differentiate flat files if they get too large
     */
    private int m_LogFileCounter = 0;

    /**
     * Name of output file name to log data
     */
    private String m_LogFilename;

    /**
     * Log folder
     */
    String m_LogFolderName;

    boolean useYawOpt;

    boolean forceUpdate = false;

    

    /** Creates new form WindEstimationPanel */
    public WindEstimationPanel(java.awt.Frame parent, boolean modal, BeliefManager newBelMgr) {
        super(parent, modal);
        initComponents();

        picDial = new BearingDial ();
        _picDial.add(picDial);
        picDial.setSize(_picDial.getWidth(), _picDial.getHeight());
        picDial.setVisible(true);
        picDial.repaint();

        estDial = new BearingDial ();
        _estDial.add(estDial);
        estDial.setSize(_estDial.getWidth(), _estDial.getHeight());
        estDial.setVisible(true);
        estDial.repaint();

        belMgr = newBelMgr;
        useYawOpt = false;
        
        m_LogFolderName = ".\\WindLogs";
        while (m_LogFolderName.endsWith ("\\") || m_LogFolderName.endsWith("/"))
            m_LogFolderName = m_LogFolderName.substring(0, m_LogFolderName.length() - 1);
        try
        {
            File outputFolder = new File (m_LogFolderName);
            if (!outputFolder.exists())
                outputFolder.mkdirs();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        m_LogFolderName += "/";
        m_LogFilename = m_LogFolderName + "WindLog_" + System.currentTimeMillis() + "_";
        
        final WindEstimationPanel panelPtr = this;
        thread = new Thread() {
            public void run ()
            {
                while (true)
                {
                    try
                    {
                        if (panelPtr.isVisible())
                            update();
                        Thread.sleep (500);
                    }
                    catch (Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            }
        };
        thread.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        _heading = new javax.swing.JLabel();
        _pitch = new javax.swing.JLabel();
        _roll = new javax.swing.JLabel();
        _vgpsn = new javax.swing.JLabel();
        _vgpse = new javax.swing.JLabel();
        _vas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        _picspeed = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        _picdir = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        _windsouth = new javax.swing.JLabel();
        _windwest = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        _estspeed = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        _estdir = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        _picDial = new javax.swing.JPanel();
        _estDial = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        _yaw = new javax.swing.JLabel();
        _useYawBox = new javax.swing.JCheckBox();

        setTitle("Wind Estimation");

        jLabel1.setText("Heading: ");

        jLabel2.setText("Pitch:");

        jLabel3.setText("Roll:");

        jLabel4.setText("V GPS N:");

        jLabel8.setText("V GPS E:");

        jLabel10.setText("V AS:");

        _heading.setText("N/A");
        _heading.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        _pitch.setText("N/A");
        _pitch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        _roll.setText("N/A");
        _roll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        _vgpsn.setText("N/A");
        _vgpsn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        _vgpse.setText("N/A");
        _vgpse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        _vas.setText("N/A");
        _vas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("deg");

        jLabel6.setText("deg");

        jLabel7.setText("deg");

        jLabel9.setText("m/s");

        jLabel11.setText("m/s");

        jLabel12.setText("m/s");

        _picspeed.setText("N/A");
        _picspeed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("m/s");

        _picdir.setText("N/A");
        _picdir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("deg");

        jLabel15.setText("Wind Speed:");

        jLabel16.setText("Wind From:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setText("PICCOLO");

        _windsouth.setText("N/A");
        _windsouth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        _windwest.setText("N/A");
        _windwest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("m/s");

        jLabel19.setText("m/s");

        jLabel20.setText("Wind South:");

        jLabel21.setText("Wind West:");

        _estspeed.setText("N/A");
        _estspeed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("m/s");

        _estdir.setText("N/A");
        _estdir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("deg");

        jLabel24.setText("Wind Speed:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setText("ESTIMATION");

        jLabel26.setText("Wind From:");

        _picDial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout _picDialLayout = new javax.swing.GroupLayout(_picDial);
        _picDial.setLayout(_picDialLayout);
        _picDialLayout.setHorizontalGroup(
            _picDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        _picDialLayout.setVerticalGroup(
            _picDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        _estDial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout _estDialLayout = new javax.swing.GroupLayout(_estDial);
        _estDial.setLayout(_estDialLayout);
        _estDialLayout.setHorizontalGroup(
            _estDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        _estDialLayout.setVerticalGroup(
            _estDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        jLabel27.setText("deg");

        jLabel28.setText("Yaw:");

        _yaw.setText("N/A");
        _yaw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        _useYawBox.setText("Use Yaw instead of Heading");
        _useYawBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _useYawBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_pitch, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_roll, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_vgpsn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_vgpse, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_vas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_useYawBox)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_windsouth, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_windwest, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_picdir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_picspeed, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_estspeed, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(_estdir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(_picDial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(_estDial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_yaw, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(_heading)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(_pitch)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(_roll)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(_vgpsn)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(_vgpse)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(_vas)
                                    .addComponent(jLabel12))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(_yaw)
                            .addComponent(jLabel27)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(_windsouth)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(_windwest)
                            .addComponent(jLabel19))
                        .addGap(14, 14, 14)
                        .addComponent(_useYawBox)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(_picspeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(_picdir)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(_estspeed)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel23)
                            .addComponent(_estdir))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_picDial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_estDial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _useYawBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__useYawBoxActionPerformed
        // TODO add your handling code here:
        useYawOpt = _useYawBox.isSelected();
        forceUpdate = true;
        update();
    }//GEN-LAST:event__useYawBoxActionPerformed


    @Override
    public void update()
    {
        if (belMgr == null)
            return;
        
        PiccoloTelemetryBelief telem = (PiccoloTelemetryBelief)belMgr.get(PiccoloTelemetryBelief.BELIEF_NAME);
        if (telem == null)
            return;

        if (lastTelem != null && (!telem.isNewerThan(lastTelem) &&  !forceUpdate))
            return;

        forceUpdate = false;
        lastTelem = telem;
        Pic_Telemetry tel = telem.getPiccoloTelemetry();
        if (tel == null)
            return;

        _heading.setText("" + tel.TrueHeading);
        _pitch.setText("" + tel.Pitch);
        _roll.setText("" + tel.Roll);
        _yaw.setText("" + tel.Yaw);

        _vgpsn.setText("" + tel.VelNorth);
        _vgpse.setText("" + tel.VelEast);
        _vas.setText("" + tel.IndAirSpeed_mps);

        _windsouth.setText ("" + tel.WindSouth);
        _windwest.setText ("" + tel.WindWest);

        double picMag = Math.sqrt (tel.WindSouth*tel.WindSouth + tel.WindWest*tel.WindWest);
        double picDir = Math.toDegrees(Math.atan2(-tel.WindWest, -tel.WindSouth));
        int picDirInt = (((int)picDir + 360) % 360);

        double vwn = 0, vwe = 0;
        if (!useYawOpt)
        {
            vwn = tel.VelNorth - tel.IndAirSpeed_mps * Math.cos(Math.toRadians(tel.Pitch)) * Math.cos(Math.toRadians(tel.TrueHeading));
            vwe = tel.VelEast - tel.IndAirSpeed_mps*Math.cos(Math.toRadians(tel.Pitch))*Math.sin(Math.toRadians(tel.TrueHeading));
        }
        else
        {
            vwn = tel.VelNorth - tel.IndAirSpeed_mps * Math.cos(Math.toRadians(tel.Pitch)) * Math.cos(Math.toRadians(tel.Yaw));
            vwe = tel.VelEast - tel.IndAirSpeed_mps*Math.cos(Math.toRadians(tel.Pitch))*Math.sin(Math.toRadians(tel.Yaw));
        }
        double estMag = Math.sqrt (vwn*vwn + vwe*vwe);
        double estDir = Math.toDegrees(Math.atan2(-vwe, -vwn));
        int estDirInt = (((int)estDir + 360) % 360);

        _picspeed.setText ("" + picMag);
        _picdir.setText ("" + picDirInt);

        _estspeed.setText ("" + estMag);
        _estdir.setText ("" + estDirInt);

        picDial.update(picDir, picMag);
        estDial.update(estDir, estMag);


        //System.out.println (tel.toLogString());
        //System.out.println ((useYawOpt?"Y":"H") + " " + picMag + " " + picDir + " " + estMag + " " + estDir);
        ensureLogFile();

        try
        {
            m_LogFileWriter.write (System.currentTimeMillis() + " " + tel.toLogString() + "\n");
            m_LogFileWriter.write ((useYawOpt?"Y":"H") + " " + picMag + " " + picDir + " " + estMag + " " + estDir + "\n");
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    private void ensureLogFile()
    {
        if (m_LogFile == null ||  m_LogFile.length() > MAX_LOG_FILE_BYTES)
        {
            //We need a new file
            try
            {
                if (m_LogFileWriter != null)
                {
                    m_LogFileWriter.flush();
                    m_LogFileWriter.close();
                }
            }
            catch (Exception e)
            {
                System.err.println("Could not flush output stream before making new flat file for Bridgeport gamma detector");
            }

            Formatter format = new Formatter();
            format.format("%1$s%2$05d%3$s", m_LogFilename, m_LogFileCounter++, ".log");
            m_LogFile = new File(format.out().toString());

            try
            {
                OutputStream ist = new FileOutputStream(m_LogFile);
                m_LogFileWriter = new BufferedWriter(new OutputStreamWriter(ist));
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _estDial;
    private javax.swing.JLabel _estdir;
    private javax.swing.JLabel _estspeed;
    private javax.swing.JLabel _heading;
    private javax.swing.JPanel _picDial;
    private javax.swing.JLabel _picdir;
    private javax.swing.JLabel _picspeed;
    private javax.swing.JLabel _pitch;
    private javax.swing.JLabel _roll;
    private javax.swing.JCheckBox _useYawBox;
    private javax.swing.JLabel _vas;
    private javax.swing.JLabel _vgpse;
    private javax.swing.JLabel _vgpsn;
    private javax.swing.JLabel _windsouth;
    private javax.swing.JLabel _windwest;
    private javax.swing.JLabel _yaw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

}
