/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.jhuapl.nstd.swarm.display;

import javax.swing.BoxLayout;
import edu.jhuapl.nstd.swarm.belief.BeliefManager;


/**
 *
 * @author xud1
 */
public class WACSVideoClientPanel extends javax.swing.JPanel 
{
    /**
     * Creates new form WACSVideoClientPanel
     */
    
    private WACSResizableVideoPanel mVideoPanel = null;
    
    public WACSVideoClientPanel(BeliefManager beliefManager) 
    {              
        initComponents();
        
        // initialize video panel
        mVideoPanel = new WACSResizableVideoPanel(beliefManager);              

        // initialize video control panel
        WACSVideoPlaybackPanel playbackPanel = new WACSVideoPlaybackPanel(mVideoPanel); 
                                
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));               
        this.add(mVideoPanel);
        this.add(playbackPanel);   
        
        addComponentListener(new java.awt.event.ComponentAdapter() 
        {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) 
            {
                mVideoPanel.estimateOptimalImageSize(evt);
            }
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(320, 364));
        setPreferredSize(new java.awt.Dimension(320, 364));
        setRequestFocusEnabled(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
