/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.jhuapl.nstd.swarm.display;

/**
 *
 * @author xud1
 */
public class WACSVideoPlaybackPanel extends javax.swing.JPanel 
{
    /**
     * Creates new form WACSVideoClientPanel
     */
    private WACSResizableVideoPanel mVideoPanel;
    
    public WACSVideoPlaybackPanel(WACSResizableVideoPanel videoPanel) 
    {       
        initComponents();          
        mVideoPanel = videoPanel;      
        playbackSlider.setEnabled(false);     
        streamButton.setEnabled(false);
        playPauseButton.setEnabled(false);      
        satCommButton.setEnabled(false);
        mVideoPanel.SetPlaybackSliderHandle(playbackSlider);    
        mVideoPanel.SetPlayPauseButtonHandle(playPauseButton);
        mVideoPanel.SetRecConversionButtonHandle(convertRecordingButton);
        mVideoPanel.SetSatCommButtonHandle(satCommButton);   
        mVideoPanel.SetStreamButtonHandle(streamButton); 
        mVideoPanel.SetRecordButtonHandle(recordButton);
        mVideoPanel.SetMsgLabelHandle(msgLabel);
        
        // register recording button event with video display panel
        recordButton.addActionListener(new java.awt.event.ActionListener() 
        {                        
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {        
                mVideoPanel.RecordButtonActionPerformed(evt);
            }
        });  
        
        // register play/pause button
        playPauseButton.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                if(playPauseButton.isSelected())
                {
                    playPauseButton.setText("Pause");
                }
                else
                {
                    playPauseButton.setText("Play");
                }
                mVideoPanel.PlayPauseButtonActionPerformed(evt);
            }
            
        });
        
        playbackButton.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mVideoPanel.PlaybackActionPerformed(evt);
            }
        });  
        
        slowDownButton.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mVideoPanel.SlowDownActionPerformed(evt);
            }
        });
        
        speedUpButton.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mVideoPanel.SpeedUpActionPerformed(evt);
            }
        });
        
        streamButton.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mVideoPanel.StreamActionPerformed(evt);
            }
        });
        
        convertRecordingButton.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mVideoPanel.ConvertVideoActionPerformed(evt);
            }            
        });
        
        satCommButton.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                if(playPauseButton.isSelected())
                {
                    playPauseButton.setSelected(false);
                    playPauseButton.setText("Play");
                }
                
                mVideoPanel.SatCommImageButton(evt);
            }
        });
        
        playbackSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() 
        {
            public void mouseDragged(java.awt.event.MouseEvent evt) 
            {
                mVideoPanel.SliderDragged(evt);
            }
        });
        
        playbackSlider.addMouseListener(new java.awt.event.MouseAdapter() 
        {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) 
            {
                mVideoPanel.SliderPositionSelected(evt);
            }
        });                
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        speedUpButton1 = new javax.swing.JButton();
        recordButton = new javax.swing.JToggleButton();
        playbackSlider = new javax.swing.JSlider();
        playPauseButton = new javax.swing.JToggleButton();
        playbackButton = new javax.swing.JToggleButton();
        speedUpButton = new javax.swing.JButton();
        slowDownButton = new javax.swing.JButton();
        streamButton = new javax.swing.JToggleButton();
        convertRecordingButton = new javax.swing.JToggleButton();
        satCommButton = new javax.swing.JToggleButton();
        msgLabel = new javax.swing.JLabel();

        speedUpButton1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        speedUpButton1.setText("Stream");
        speedUpButton1.setToolTipText("");
        speedUpButton1.setMaximumSize(new java.awt.Dimension(48, 20));
        speedUpButton1.setMinimumSize(new java.awt.Dimension(48, 20));
        speedUpButton1.setPreferredSize(new java.awt.Dimension(48, 20));

        setMaximumSize(new java.awt.Dimension(32767, 82));
        setMinimumSize(new java.awt.Dimension(320, 95));
        setPreferredSize(new java.awt.Dimension(320, 95));

        recordButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        recordButton.setForeground(new java.awt.Color(255, 0, 0));
        recordButton.setText("Rec");
        recordButton.setToolTipText("Start or pause the recorder");
        recordButton.setMaximumSize(new java.awt.Dimension(48, 20));
        recordButton.setMinimumSize(new java.awt.Dimension(48, 20));
        recordButton.setPreferredSize(new java.awt.Dimension(60, 20));
        recordButton.setRequestFocusEnabled(false);

        playbackSlider.setToolTipText("Drag to select frame");
        playbackSlider.setValue(0);
        playbackSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playbackSlider.setPreferredSize(new java.awt.Dimension(240, 23));

        playPauseButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        playPauseButton.setText("Pause");
        playPauseButton.setToolTipText("Start or pause current playback");
        playPauseButton.setMaximumSize(new java.awt.Dimension(80, 20));
        playPauseButton.setMinimumSize(new java.awt.Dimension(80, 20));
        playPauseButton.setPreferredSize(new java.awt.Dimension(80, 20));

        playbackButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        playbackButton.setForeground(new java.awt.Color(51, 153, 0));
        playbackButton.setText("Playback");
        playbackButton.setToolTipText("Enter/exit video playback mode");
        playbackButton.setMaximumSize(new java.awt.Dimension(80, 20));
        playbackButton.setMinimumSize(new java.awt.Dimension(80, 20));
        playbackButton.setPreferredSize(new java.awt.Dimension(80, 20));

        speedUpButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        speedUpButton.setText(">>");
        speedUpButton.setToolTipText("Increase playback speed by a factor of 2");
        speedUpButton.setMaximumSize(new java.awt.Dimension(48, 20));
        speedUpButton.setMinimumSize(new java.awt.Dimension(48, 20));
        speedUpButton.setPreferredSize(new java.awt.Dimension(48, 20));

        slowDownButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        slowDownButton.setText("<<");
        slowDownButton.setToolTipText("Decrease playback speed by a factor of 2");
        slowDownButton.setMaximumSize(new java.awt.Dimension(48, 20));
        slowDownButton.setMinimumSize(new java.awt.Dimension(48, 20));
        slowDownButton.setPreferredSize(new java.awt.Dimension(48, 20));

        streamButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        streamButton.setForeground(new java.awt.Color(51, 51, 255));
        streamButton.setText("Stop Streaming");
        streamButton.setToolTipText("Start or stop streaming");
        streamButton.setMaximumSize(new java.awt.Dimension(48, 20));
        streamButton.setMinimumSize(new java.awt.Dimension(48, 20));
        streamButton.setPreferredSize(new java.awt.Dimension(60, 20));
        streamButton.setRequestFocusEnabled(false);

        convertRecordingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/jhuapl/nstd/swarm/display/snap-converter-icon.png"))); // NOI18N
        convertRecordingButton.setToolTipText("Convert recordings to avi files");
        convertRecordingButton.setOpaque(true);

        satCommButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/jhuapl/nstd/swarm/display/snapshot.png"))); // NOI18N
        satCommButton.setToolTipText("Request SatComm image");
        satCommButton.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playbackSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(slowDownButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playPauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playbackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streamButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(speedUpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(satCommButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(convertRecordingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playbackSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgLabel)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertRecordingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satCommButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playPauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(slowDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speedUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JToggleButton convertRecordingButton;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JToggleButton playPauseButton;
    private javax.swing.JToggleButton playbackButton;
    private javax.swing.JSlider playbackSlider;
    private javax.swing.JToggleButton recordButton;
    private javax.swing.JToggleButton satCommButton;
    private javax.swing.JButton slowDownButton;
    private javax.swing.JButton speedUpButton;
    private javax.swing.JButton speedUpButton1;
    private javax.swing.JToggleButton streamButton;
    // End of variables declaration//GEN-END:variables
}
