//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WACS_ExternalDisplay.rc
//
#define IDC_MYICON                      2
#define IDD_CRATRGUI_DIALOG             102
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDC_CRATRGUI                    109
#define IDC_MENUBAR                     109
#define IDC_ACCELERATORS                109
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        129
#define IDD_CONFIRMDIALOG               130
#define IDS_MOSAICFILTER                135
#define IDS_SHPFILTER                   136
#define IDC_CURSOR1                     136
#define IDB_BITMAP1                     149
#define IDC_MAGIC_WAND                  150
#define IDI_ICON1                       151
#define IDI_ICON2                       153
#define IDD_LOGBOX                      154
#define IDD_RAWTABLES                   155
#define IDC_MOSAIC_VIEW                 1001
#define IDC_MAP_VIEW                    1001
#define IDC_CONFIRMTEXT                 1002
#define ID_YES                          1003
#define ID_NO                           1004
#define IDC_SIMULATEMOSAICBUTTON        1005
#define IDC_IMGFILENAMEINPUT            1006
#define IDC_WFFILENAMEINPUT             1007
#define IDC_SHPFILENAMEINPUT            1008
#define IDC_MOSAIC_THUMBNAIL            1015
#define IDC_SELECTSHAPE                 1016
#define IDC_NEWSHAPE                    1018
#define IDC_NEWCRATER                   1018
#define IDC_AUTOCHECKBOX                1019
#define IDC_AUTOCRATERBOX               1019
#define IDC_MANUALCHECKBOX              1020
#define IDC_MANUALCRATERBOX             1020
#define IDC_EDITSHAPE                   1021
#define IDC_MOUSECONTROL                1022
#define IDC_DELETESHAPE                 1023
#define IDC_CUSTOM1                     1024
#define IDC_NEWANOMALY                  1024
#define IDC_EXPORTMOSAIC                1025
#define IDC_IMPORTSHPFILE               1026
#define IDC_BACKGROUNDBUTTON            1026
#define IDC_NEWUXO                      1027
#define IDC_CALIBRATEBUTTON2            1031
#define IDC_QUEUEHOLDER                 1032
#define IDC_LABEL                       1038
#define IDC_AUTOANOMALYBOX              1039
#define IDC_MANUALANOMALYBOX            1040
#define IDC_SLINGSHOTBOX                1041
#define IDC_SLINGSHOTSPEEDSLIDER        1042
#define IDC_FINDMOSAICBUTTON            1043
#define IDC_FINDSHPBUTTON               1044
#define IDC_AUTOUXOBOX                  1045
#define IDC_MANUALUXOBOX                1046
#define IDC_RESETCAMERA                 1047
#define IDC_SLINGSHOTPAUSED             1048
#define IDC_UNDO                        1049
#define IDC_TIMERLABEL                  1050
#define IDC_SELECTEDLABEL               1051
#define IDC_MOUSELABEL                  1052
#define IDC_TIMEROUTPUT                 1053
#define IDC_SELECTEDOUTPUT              1054
#define IDC_MOUSEOUTPUT                 1055
#define IDC_SLINGSHOTREVERSE            1065
#define IDC_QUEUESIZE                   1068
#define IDC_HIDEBUTTON                  1069
#define IDC_LAYERSBOX                   1070
#define IDC_CAMERABOX                   1071
#define IDC_TOOLSBOX                    1072
#define IDC_QUEUESIZELABEL              1073
#define IDC_AUTOLABEL                   1074
#define IDC_MANUALLABEL                 1075
#define IDC_CRATERLABEL                 1076
#define IDC_ANOMALYLABEL                1077
#define IDC_UXOLABEL                    1078
#define IDC_MAGICWAND                   1079
#define IDC_LOGBOX                      1085
#define IDC_LOGLIST                     1085
#define IDC_JOYSTICK_CONNECT            1087
#define IDC_BELIEFCOMBO                 1089
#define IDC_FIELDLABEL1                 1090
#define IDC_FIELDLABEL2                 1092
#define IDC_FIELDVALUE2                 1093
#define IDC_FIELDLABEL3                 1094
#define IDC_FIELDVALUE3                 1095
#define IDC_FIELDLABEL4                 1096
#define IDC_FIELDVALUE4                 1097
#define IDC_FIELDLABEL5                 1098
#define IDC_FIELDVALUE5                 1099
#define IDC_FIELDVALUE1                 1101
#define IDC_FIELDLABEL6                 1102
#define IDC_FIELDVALUE6                 1103
#define IDC_FIELDLABEL7                 1106
#define IDC_FIELDVALUE7                 1107
#define IDC_FIELDLABEL8                 1108
#define IDC_FIELDVALUE8                 1109
#define IDC_FIELDLABEL9                 1110
#define IDC_FIELDVALUE9                 1111
#define IDC_FIELDLABEL10                1114
#define IDC_FIELDVALUE10                1115
#define IDC_FIELDLABEL11                1116
#define IDC_FIELDVALUE11                1117
#define IDC_FIELDLABEL12                1120
#define IDC_FIELDVALUE12                1121
#define IDC_FIELDLABEL13                1122
#define IDC_FIELDVALUE13                1123
#define IDC_FIELDLABEL14                1126
#define IDC_FIELDVALUE14                1127
#define IDC_FIELDLABEL15                1128
#define IDC_FIELDVALUE15                1129
#define IDC_FIELDLABEL16                1132
#define IDC_FIELDVALUE16                1133
#define IDC_FIELDLABEL17                1134
#define IDC_FIELDVALUE17                1135
#define IDC_FIELDLABEL18                1138
#define IDC_FIELDVALUE18                1139
#define IDC_FIELDLABEL19                1140
#define IDC_FIELDVALUE19                1141
#define IDC_FIELDLABEL20                1142
#define IDC_FIELDVALUE20                1143
#define IDC_FIELDLABEL21                1146
#define IDC_FIELDVALUE21                1147
#define IDC_FIELDLABEL22                1148
#define IDC_FIELDVALUE22                1149
#define ID_CONFIGURE_INPUT              32771
#define ID_IMPORT_MOSAIC                32774
#define ID_IMPORT_SHAPEFILE             32775
#define ID_CONFIGURE_SETTINGS           32776
#define ID_LOG_LOG                      32777
#define ID_OPTIONS                      32778
#define ID_OPTIONS_SHOWRAWTABLES        32779
#define ID_OPTIONS_DISPLAYSHADOW        32780
#define ID_Menu                         32781
#define ID_OPTIONS_DISPLAYPGCS          32782
#define ID_OPTIONS_DISPLAYORBIT         32783
#define ID_OPTIONS_USE_PIC_TEL          32784
#define ID_OPTIONS_USEPICTEL            32785
#define ID_OPTIONS_RESETCAMERA          32786
#define ID_OPTIONS_DISPLAYPARTICLEDETECTIONS 32787
#define ID_OPTIONS_DISPLAYCHEMICALDETECTIONS 32788
#define ID_OPTIONS_DISPLAYPREDICTEDCLOUD 32789
#define ID_OPTIONS_DISPLAYEXPLOSIONINDICATOR 32790
#define ID_OPTIONS_DISPLAYMETDATA       32791
#define ID_OPTIONS_DISPLAYEXPLOSIONTIME 32792
#define ID_OPTIONS_DISPLAYIREXPLOSIONALGORITHMENABLED 32793
#define ID_OPTIONS_DISPLAYSENSOROVERLAYS 32794
#define ID_OPTIONS_DISPLAYPROPOGATEDDETECTIONS 32795
#define ID_OPTIONS_PAUSEDETECTIONPROPOGATION 32796
#define ID_UNITS_ALTITUDEINFEET         32799
#define ID_SWARMSPY_RESTARTLOGGING      32800
#define ID_SWARMSPY_PAUSEREPLAY         32801
#define ID_VIEW_RESETVIEW               32802
#define ID_SWARMSPY_RESTARTREPLAY       32803
#define ID_SWARMSPY_PAUSEALL            32804
#define ID_SWARMSPY_UNPAUSEALL          32805
#define ID_VIEW_DISPLAYLOITERAPPROACHPATH 32806
#define ID_OPTIONS_DISPLAYLOITERAPPROACHPATH 32807
#define ID_VIDEOCAPTURE_ENABLED         32808
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
