/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JogPanel.java
 *
 * Created on Jul 10, 2009, 11:18:27 AM
 */
package edu.jhuapl.nstd.sti.ptutracker.app;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author southmk1
 */
public class JogPanel extends javax.swing.JPanel {

    private double _xPos = 0.0;
    private double _yPos = 0.0;
    private boolean mouseDown = false;

    /** Creates new form JogPanel */
    public JogPanel() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;

        int width = this.getWidth() - 1;
        int height = this.getHeight() - 1;

        //draw box
        Rectangle2D panBorder = new Rectangle2D.Double(0, 0, width, height);
        g2.setPaint(Color.WHITE);
        g2.fill(panBorder);
        g2.setPaint(Color.BLACK);
        g2.draw(panBorder);


        //draw cross hairs
        g2.setStroke(new BasicStroke(1.0f,
                BasicStroke.CAP_BUTT,
                BasicStroke.JOIN_MITER,
                10.0f, new float[]{10.0f}, 0.0f));

        g2.draw(new Line2D.Double(width / 2, 0, width / 2, height));
        g2.draw(new Line2D.Double(0, height / 2, width, height / 2));

        g2.setStroke(new BasicStroke(2));
        //draw cursor
        g2.draw(new Line2D.Double((this.getXPos()+.5)*width-10, (this.getYPos()+.5)*height, (this.getXPos()+.5)*width+10, (this.getYPos()+.5)*height));
        g2.draw(new Line2D.Double((this.getXPos()+.5)*width, (this.getYPos()+.5)*height-10, (this.getXPos()+.5)*width, (this.getYPos()+.5)*height+10));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            _xPos = (double) evt.getX() / this.getWidth()-0.5;
            _yPos = (double) evt.getY() / this.getHeight()-0.5;
            mouseDown = true;
            
        }
        repaint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON1) {
            _xPos = 0.0;
            _yPos = 0.0;
            mouseDown = false;
        }
        repaint();
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if (mouseDown) {
            _xPos = (double) evt.getX() / this.getWidth()-0.5;
            _yPos = (double) evt.getY() / this.getHeight()-0.5;
        }
        repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * @return the _xPos
     */
    public double getXPos() {
        return _xPos;
    }

    /**
     * @param xPos the _xPos to set
     */
    public void setXPos(double xPos) {
        this._xPos = xPos;
    }

    /**
     * @return the _yPos
     */
    public double getYPos() {
        return _yPos;
    }

    /**
     * @param yPos the _yPos to set
     */
    public void setYPos(double yPos) {
        this._yPos = yPos;
    }
}
