/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanPanel.java
 *
 * Created on Jul 10, 2009, 2:55:28 AM
 */
package edu.jhuapl.nstd.sti.ptutracker.app;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;

/**
 *
 * @author southmk1
 */
public class PanPanel extends javax.swing.JPanel {

    private int panDegrees = 0;
    private int beamWidth;

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;

        //DRAW CIRCLE
        Ellipse2D panBorder = new Ellipse2D.Double(0, 0, this.getWidth() - 1, this.getHeight() - 1);
        g2.setPaint(Color.WHITE);
        g2.fill(panBorder);
        g2.setPaint(Color.BLACK);
        g2.draw(panBorder);

        //draw lines for angle
        g2.setPaint(Color.RED);
        //calculate endpoints
        int r = this.getWidth() / 2;
        int centerx = this.getWidth() / 2;
        int centery = this.getHeight() / 2;
        double degrees = getPanDegrees()-900;
        int dx = (int) (Math.cos(Math.toRadians(degrees / 10.0)) * r);
        int dy = (int) (Math.sin(Math.toRadians(degrees / 10.0)) * r);
        g2.draw(new Line2D.Double(centerx, centery, centerx + dx, centery + dy));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(100, 100));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panDegrees
     */
    public int getPanDegrees() {
        return panDegrees;
    }

    /**
     * @param panDegrees the panDegrees to set
     */
    public void setPanDegrees(int panDegrees) {
        this.panDegrees = panDegrees;
        repaint();
    }

    /**
     * @return the beamWidth
     */
    public int getBeamWidth() {
        return beamWidth;
    }

    /**
     * @param beamWidth the beamWidth to set
     */
    public void setBeamWidth(int beamWidth) {
        this.beamWidth = beamWidth;
        repaint();
    }

    /** Creates new form PanPanel */
    public PanPanel() {
        initComponents();

    }
}
