/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PTUConnectionInfo.java
 *
 * Created on Jul 9, 2009, 6:37:47 PM
 */

package edu.jhuapl.nstd.sti.ptutracker.app;

import java.net.Inet4Address;
import javax.swing.JOptionPane;

/**
 *
 * @author southmk1
 */
public class PTUConnectionInfo extends javax.swing.JFrame {

    PTUTrackerView ptuView;
    /** Creates new form PTUConnectionInfo */
    public PTUConnectionInfo(PTUTrackerView ptuView) {
        this.setTitle("Connection Information");
        initComponents();
        this.ptuView = ptuView;
        initFields();
    }

     public void initFields() {
        //init fields

        //int apNum, String port_or_ipAddr, int baud_or_port, boolean usingTCP)
        jtfPilotId.setText(""+ApplicationState.getApplicationState().getPilotId());
        jtfIpOrCom.setText(ApplicationState.getApplicationState().getComOrIp());
        jtfPortOrBaud.setText(ApplicationState.getApplicationState().getPortOrBaud());
        jtbIsTcp.setSelected(ApplicationState.getApplicationState().isIsTCP());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtbIsTcp = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jtfPilotId = new javax.swing.JTextField();
        jtfIpOrCom = new javax.swing.JTextField();
        jtfPortOrBaud = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jbOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.jhuapl.nstd.sti.ptutracker.app.PTUTrackerApp.class).getContext().getResourceMap(PTUConnectionInfo.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jtbIsTcp.setSelected(true);
        jtbIsTcp.setText(resourceMap.getString("jtbIsTcp.text")); // NOI18N
        jtbIsTcp.setName("jtbIsTcp"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jtfPilotId.setText(resourceMap.getString("jtfPilotId.text")); // NOI18N
        jtfPilotId.setName("jtfPilotId"); // NOI18N

        jtfIpOrCom.setText(resourceMap.getString("jtfIpOrCom.text")); // NOI18N
        jtfIpOrCom.setName("jtfIpOrCom"); // NOI18N

        jtfPortOrBaud.setText(resourceMap.getString("jtfPortOrBaud.text")); // NOI18N
        jtfPortOrBaud.setName("jtfPortOrBaud"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1", "COM2", "COM3", "COM4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jbOk.setText(resourceMap.getString("jbOk.text")); // NOI18N
        jbOk.setName("jbOk"); // NOI18N
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbOk)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbIsTcp)
                    .addComponent(jtfPilotId)
                    .addComponent(jtfPortOrBaud, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfIpOrCom))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPilotId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jtfIpOrCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPortOrBaud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jtbIsTcp)
                .addGap(33, 33, 33)
                .addComponent(jbOk)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
             //try to parse everything
        int pilotId;
        String IpOrCom;
        int portOrBaud;
        boolean isTcp;

        isTcp = jtbIsTcp.isSelected();

        try {
            pilotId = Integer.parseInt(jtfPilotId.getText());
            portOrBaud = Integer.parseInt(jtfPortOrBaud.getText());
            if (isTcp) {
                Inet4Address.getByName(jtfIpOrCom.getText());
            } else {
                if (!jtfIpOrCom.getText().contains("COM")) {
                    throw new Exception("Bad Com Port");
                }

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error Details:\n"
				+ ex.getMessage(), "Exception!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ApplicationState.getApplicationState().setPilotId(pilotId);
        ApplicationState.getApplicationState().setTrackerComPort(jComboBox1.getSelectedItem().toString());
        ApplicationState.getApplicationState().setComOrIp(jtfIpOrCom.getText());
        ApplicationState.getApplicationState().setPortOrBaud(jtfPortOrBaud.getText());
        ApplicationState.getApplicationState().setIsTCP(isTcp);

        ApplicationState.saveToFile();
        
        ptuView.initMembers();
    }//GEN-LAST:event_jbOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbOk;
    private javax.swing.JCheckBox jtbIsTcp;
    private javax.swing.JTextField jtfIpOrCom;
    private javax.swing.JTextField jtfPilotId;
    private javax.swing.JTextField jtfPortOrBaud;
    // End of variables declaration//GEN-END:variables

}
