package edu.jhuapl.nstd.cbrnPods.messages;

import java.util.Vector;
import edu.jhuapl.spectra.AETNAResult.IsotopeConcentraion;

/**
 * Parent class for the Detection Report messages generated by
 * the Bladewerx and Bridgeport sensors when using the
 * AETNA template library.
 * 
 * @author olsoncc1
 *
 */
public class AETNADetectionReportMessage extends cbrnPodMsg
{
    /**
     * Isotopes detected
     */
    protected Vector<IsotopeConcentraion> m_Isotopes = new Vector<IsotopeConcentraion>();
    
    public AETNADetectionReportMessage()
    {
    	super();
    }
    
    protected AETNADetectionReportMessage(int sensorType, int messageType, int length)
    {
    	super(sensorType, messageType, length);
    	clear();
    }
    
    private void clear()
    {
        timestampMs = 0;
        m_Isotopes.clear();
    }
    
    public Vector<IsotopeConcentraion> accessIsotopes()
    {
        return m_Isotopes;
    }

    public void addIsotope(String isotope, double concentration)
    {
        IsotopeConcentraion newPair = new IsotopeConcentraion(isotope, (float)concentration);
        m_Isotopes.add(newPair);
    }
    
    @Override
    public void parseBioPodMessage(cbrnPodMsg m)
    {
        AETNADetectionReportMessage msg = (AETNADetectionReportMessage) m;

        this.timestampMs = msg.timestampMs;
        for (int i = 0; i < msg.m_Isotopes.size(); i ++)
        {
            addIsotope(msg.m_Isotopes.get(i).isotope, msg.m_Isotopes.get(i).concentration);
        }
        
        this.messageType = msg.messageType;
        this.validMessage = true;
    }
}