/*
 * BridgeportOutputDisplay.java
 *
 * Created on December 11, 2009, 12:05 PM
 */

package edu.jhuapl.nstd.cbrnPods.Bridgeport;

import edu.jhuapl.nstd.cbrnPods.Bridgeport.BridgeportGammaDetectorEthernetInterface;
import edu.jhuapl.nstd.cbrnPods.Bridgeport.GammaCountRates;
import edu.jhuapl.nstd.cbrnPods.RNHistogram;
import edu.jhuapl.nstd.cbrnPods.Bridgeport.BridgeportEthernetMessageListener;
import edu.jhuapl.nstd.swarm.belief.BeliefManager;
import edu.jhuapl.nstd.swarm.belief.CountItem;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 * Test display program for Bridgeport sensor  
 *
 * @author  humphjc1
 */
public class BridgeportOutputDisplay extends javax.swing.JFrame implements BridgeportEthernetMessageListener{

    BridgeportOutputDisplayGraph m_DisplayGraph = new BridgeportOutputDisplayGraph();
    
    BridgeportGammaDetectorEthernetInterface m_Interface = new BridgeportGammaDetectorEthernetInterface((BeliefManager)null);
    
    
    /** Creates new form BridgeportOutputDisplay */
    public BridgeportOutputDisplay() {
        initComponents();
        
        ButtonGroup histoType = new ButtonGroup();
        histoType.add(m_LiveButton);
        histoType.add(m_AccumButton);
        
        m_DisplayGraph.setSize(m_Panel.getWidth(), m_Panel.getHeight());
        m_Panel.add (m_DisplayGraph);
        this.setVisible(true);
        
        m_Interface.addBridgeportMessageListener ( this);
    }

    
    @Override
    public void handleHistogramMessage(RNHistogram m)
    {
        m_DisplayGraph.updateCurrentHistogram (m);
        
        if (m_DisplayGraph.getAccumulatingHistogram() == null)
            m_DisplayGraph.addAccumulatingHistogram(m.getCopyOfHistogram());
    }

    @Override
    public void handleStatisticsMessage(GammaEthernetCountRates m) 
    {
        m_statOut1.setText(" " + m.getRealTicks());
        m_statOut2.setText(" " + m.getNumEvents());
        m_statOut3.setText(" " + m.getNumTriggers());
        m_statOut4.setText(" " + m.getDeadTicks());
        m_statOut5.setText(" " + m.getRealTime());
        m_statOut6.setText(" " + m.getEventRate());
        m_statOut7.setText(" " + m.getTriggerRate());
        m_statOut8.setText(" " + m.getDeadTimeFraction());
        m_statOut9.setText(" " + m.getInputRate());
    }


    @Override
    public void handleCalibrationMessage(GammaCalibration m)
    {
        m_calibOut1.setText (" " + m.getADC_Speed());
        m_calibOut2.setText (" " + m.getNumADC_Bits());
        m_calibOut3.setText (" " + m.getADC_FSR());
        m_calibOut4.setText (" " + m.getGain());
        m_calibOut5.setText (" " + m.getMCA_CurrFSR());
        m_calibOut6.setText (" " + m.getMCA_CurrMax());
        m_calibOut7.setText (" " + m.getChargePerUnit());
        m_calibOut8.setText (" " + m.getDC_Offset());
        m_calibOut9.setText (" " + m.getTemperature());
        m_calibOut10.setText (" " + m.getMCA_AnodeCurrent());
        m_calibOut11.setText (" " + m.getMCA_ROI_Avg());
        m_calibOut12.setText (" " + m.getNumHistBytes());
        m_calibOut13.setText (" " + m.getNumListBytes());
        m_calibOut14.setText (" " + m.getNumTraceBytes());
        m_calibOut15.setText (" " + m.getNumModule6Bytes());
        m_calibOut16.setText (" " + m.getPacketCounter());
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        m_statOut8 = new javax.swing.JLabel();
        m_statOut1 = new javax.swing.JLabel();
        m_statOut2 = new javax.swing.JLabel();
        m_statOut3 = new javax.swing.JLabel();
        m_statOut4 = new javax.swing.JLabel();
        m_statOut5 = new javax.swing.JLabel();
        m_statOut6 = new javax.swing.JLabel();
        m_statOut7 = new javax.swing.JLabel();
        m_statOut9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        m_Panel = new javax.swing.JPanel();
        m_LiveButton = new javax.swing.JRadioButton();
        m_AccumButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        m_calibOut1 = new javax.swing.JLabel();
        m_calibOut2 = new javax.swing.JLabel();
        m_calibOut3 = new javax.swing.JLabel();
        m_calibOut4 = new javax.swing.JLabel();
        m_calibOut5 = new javax.swing.JLabel();
        m_calibOut6 = new javax.swing.JLabel();
        m_calibOut7 = new javax.swing.JLabel();
        m_calibOut8 = new javax.swing.JLabel();
        m_calibOut9 = new javax.swing.JLabel();
        m_calibOut10 = new javax.swing.JLabel();
        m_calibOut11 = new javax.swing.JLabel();
        m_calibOut12 = new javax.swing.JLabel();
        m_calibOut13 = new javax.swing.JLabel();
        m_calibOut14 = new javax.swing.JLabel();
        m_calibOut15 = new javax.swing.JLabel();
        m_calibOut16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Bridgeport Data");
        setMinimumSize(new java.awt.Dimension(100, 100));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Statistics Data");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Real Ticks");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Events");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Triggers");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dead Ticks");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Real Time");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Event Rate");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Trigger Rate");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Dead Time Frac");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Input Rate");

        m_statOut8.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut8.setText(" ");
        m_statOut8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut8.setOpaque(true);

        m_statOut1.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut1.setText(" ");
        m_statOut1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut1.setOpaque(true);

        m_statOut2.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut2.setText(" ");
        m_statOut2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut2.setOpaque(true);

        m_statOut3.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut3.setText(" ");
        m_statOut3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut3.setOpaque(true);

        m_statOut4.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut4.setText(" ");
        m_statOut4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut4.setOpaque(true);

        m_statOut5.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut5.setText(" ");
        m_statOut5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut5.setOpaque(true);

        m_statOut6.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut6.setText(" ");
        m_statOut6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut6.setOpaque(true);

        m_statOut7.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut7.setText(" ");
        m_statOut7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut7.setOpaque(true);

        m_statOut9.setBackground(new java.awt.Color(255, 255, 255));
        m_statOut9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_statOut9.setText(" ");
        m_statOut9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_statOut9.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setText("Histogram Data");

        javax.swing.GroupLayout m_PanelLayout = new javax.swing.GroupLayout(m_Panel);
        m_Panel.setLayout(m_PanelLayout);
        m_PanelLayout.setHorizontalGroup(
            m_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        m_PanelLayout.setVerticalGroup(
            m_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        m_LiveButton.setSelected(true);
        m_LiveButton.setText("Live Data");
        m_LiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_LiveButtonActionPerformed(evt);
            }
        });

        m_AccumButton.setText("Accumulated Data");
        m_AccumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_AccumButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Log Scale Y");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ADC Speed");

        m_calibOut1.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut1.setText(" ");
        m_calibOut1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut1.setOpaque(true);

        m_calibOut2.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut2.setText(" ");
        m_calibOut2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut2.setOpaque(true);

        m_calibOut3.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut3.setText(" ");
        m_calibOut3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut3.setOpaque(true);

        m_calibOut4.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut4.setText(" ");
        m_calibOut4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut4.setOpaque(true);

        m_calibOut5.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut5.setText(" ");
        m_calibOut5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut5.setOpaque(true);

        m_calibOut6.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut6.setText(" ");
        m_calibOut6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut6.setOpaque(true);

        m_calibOut7.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut7.setText(" ");
        m_calibOut7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut7.setOpaque(true);

        m_calibOut8.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut8.setText(" ");
        m_calibOut8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut8.setOpaque(true);

        m_calibOut9.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut9.setText(" ");
        m_calibOut9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut9.setOpaque(true);

        m_calibOut10.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut10.setText(" ");
        m_calibOut10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut10.setOpaque(true);

        m_calibOut11.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut11.setText(" ");
        m_calibOut11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut11.setOpaque(true);

        m_calibOut12.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut12.setText(" ");
        m_calibOut12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut12.setOpaque(true);

        m_calibOut13.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut13.setText(" ");
        m_calibOut13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut13.setOpaque(true);

        m_calibOut14.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut14.setText(" ");
        m_calibOut14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut14.setOpaque(true);

        m_calibOut15.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut15.setText(" ");
        m_calibOut15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut15.setOpaque(true);

        m_calibOut16.setBackground(new java.awt.Color(255, 255, 255));
        m_calibOut16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_calibOut16.setText(" ");
        m_calibOut16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        m_calibOut16.setOpaque(true);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("# ADC Bits");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("ADC FSR");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Gain");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("MCA Curr FSR");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("MCA Curr Max");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Charge / Unit");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("DC Offset");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Temperature");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("MCA Anode Curr");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("MCA ROI Avg");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("# Hist Bytes");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("# Listmode Bytes");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("# Trace Bytes");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("# Module6 Bytes");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Packet Counter");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel28.setText("Calibration Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_statOut1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(m_statOut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_statOut3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_statOut4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_statOut5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_statOut6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_statOut7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_statOut8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_statOut9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(m_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel11)
                        .addGap(84, 84, 84)
                        .addComponent(m_LiveButton)
                        .addGap(18, 18, 18)
                        .addComponent(m_AccumButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_calibOut8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_calibOut12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_calibOut16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(347, 347, 347))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel28)
                .addContainerGap(743, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(m_LiveButton)
                    .addComponent(m_AccumButton)
                    .addComponent(jButton1)
                    .addComponent(jCheckBox1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(m_statOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(m_statOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(m_statOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(m_statOut4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(m_statOut5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(m_statOut6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(m_statOut7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(m_statOut8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(m_statOut9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(m_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(m_calibOut9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(m_calibOut10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_calibOut12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(m_calibOut13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(m_calibOut14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(m_calibOut15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(m_calibOut16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void m_LiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_LiveButtonActionPerformed

    m_DisplayGraph.chooseLiveHistogram();
}//GEN-LAST:event_m_LiveButtonActionPerformed

private void m_AccumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_AccumButtonActionPerformed
    
    m_DisplayGraph.chooseAccumHistogram();
}//GEN-LAST:event_m_AccumButtonActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// 
    int opt = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    if (opt == JOptionPane.NO_OPTION)
        return;
    
    m_Interface.shutdown();
    
    int maxLoops = 20;
    int loopCtr = 0;
    while (m_Interface.isRunning())
    {
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
        if (loopCtr ++ > maxLoops)
        {
            break;
        }
    }
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    // TODO add your handling code here:
    m_DisplayGraph.selectLogScale (jCheckBox1.isSelected());
}//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BridgeportOutputDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton m_AccumButton;
    private javax.swing.JRadioButton m_LiveButton;
    private javax.swing.JPanel m_Panel;
    private javax.swing.JLabel m_calibOut1;
    private javax.swing.JLabel m_calibOut10;
    private javax.swing.JLabel m_calibOut11;
    private javax.swing.JLabel m_calibOut12;
    private javax.swing.JLabel m_calibOut13;
    private javax.swing.JLabel m_calibOut14;
    private javax.swing.JLabel m_calibOut15;
    private javax.swing.JLabel m_calibOut16;
    private javax.swing.JLabel m_calibOut2;
    private javax.swing.JLabel m_calibOut3;
    private javax.swing.JLabel m_calibOut4;
    private javax.swing.JLabel m_calibOut5;
    private javax.swing.JLabel m_calibOut6;
    private javax.swing.JLabel m_calibOut7;
    private javax.swing.JLabel m_calibOut8;
    private javax.swing.JLabel m_calibOut9;
    private javax.swing.JLabel m_statOut1;
    private javax.swing.JLabel m_statOut2;
    private javax.swing.JLabel m_statOut3;
    private javax.swing.JLabel m_statOut4;
    private javax.swing.JLabel m_statOut5;
    private javax.swing.JLabel m_statOut6;
    private javax.swing.JLabel m_statOut7;
    private javax.swing.JLabel m_statOut8;
    private javax.swing.JLabel m_statOut9;
    // End of variables declaration//GEN-END:variables

}
