package edu.jhuapl.nstd.swarm.display.geoimageryfetcher;

import edu.jhuapl.jlib.math.Altitude;
import edu.jhuapl.jlib.math.Angle;
import edu.jhuapl.jlib.math.Latitude;
import edu.jhuapl.jlib.math.Length;
import edu.jhuapl.jlib.math.Longitude;
import edu.jhuapl.jlib.math.position.LatLonAltPosition;

public class GeoImageryTestFrame extends javax.swing.JFrame
{
    private GeoImageryCanvas m_canvas;

    /** Creates new form GeoImageryTestFrame */
    public GeoImageryTestFrame()
    {
        initComponents();

        m_canvas = new GeoImageryCanvas(5,
                                        new Length(10.0, Length.MILES),
                                        800,
                                        600,
                                        /*new LatLonAltPosition(new Latitude(40.103725, Angle.DEGREES),
                                                              new Longitude(-113.189115, Angle.DEGREES),
                                                              Altitude.ZERO),*/
                                        new LatLonAltPosition(new Latitude(33, Angle.DEGREES),
                                                              new Longitude(66, Angle.DEGREES),
                                                              Altitude.ZERO),
                                        "./images/",
                                        false,
                                        1, 19);


        getContentPane().add(m_canvas);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        if (m_canvas != null)
            m_canvas.setSize (this.getSize());
    }//GEN-LAST:event_formComponentResized

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeoImageryTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
