/*--------------------------------------------------------------------------*/
/*                                                                          */
/*                          OCTEC LTD (c)                                   */
/*                          =========                                       */
/*                                                                          */
/*  File        :   A104_ErrorCodes.h                                       */
/*                                                                          */
/*  Owner       :   Gordon Smith                                            */
/*                                                                          */
/*  Description :   User-defined error codes for the Adept104 device driver.*/
/*                                                                          */
/*--------------------------------------------------------------------------*/
/*
*$Header:   L:/DESIGN/in5201/14/217/h/VCS/A104_ErrorCodes.h_V   1.1   May 23 2006 14:21:44   SmithGo  $
*
*$Log:   L:/DESIGN/in5201/14/217/h/VCS/A104_ErrorCodes.h_V  $
*
*   Rev 1.1   May 23 2006 14:21:44   SmithGo
*   Force 8 byte structure alignment
*
*   Rev 1.2   May 23 2006 13:59:00   SmithGo
*   Force 8 byte structure alignment
*
*   Rev 1.1   Feb 14 2006 16:32:38   SmithGo
*   Events. DPR -> AVT copy fix.  IEEE support for EXIF
*
*   Rev 1.0   Oct 15 2004 07:56:54   GordonSm
*   Initial revision (in PVCS)
*
*---------------------------------------------------------------------------*/

#if !defined(__A104_ErrorCodes_h__INCLUDED_)

#define     __A104_ErrorCodes_h__INCLUDED_

////////////////////////////////////////////////////////////////////////////

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

////////////////////////////////////////////////////////////////////////////
//  Include Files

#include    "BitMasks.h"                    //  BIT29, BIT30, BIT31

////////////////////////////////////////////////////////////////////////////
//  Global Definitions

//  Error code severity levels (from ntstatus.h, a Microsoft-supplied file).
#if !defined(__enumErrorCodeSeverity__DEFINED_)

enum        enumErrorCodeSeverity
                    {
                        ECS_SUCCESS,

                        ECS_INFORMATIONAL,
                        ECS_WARNING,
                        ECS_ERROR,
                    };

#define     __enumErrorCodeSeverity__DEFINED_

#endif  //  #if !defined(__enumErrorCodeSeverity__DEFINED_)

//  By starting the error codes from BIT29 there should be no conflict with
//  error codes generated by the system (see GetLastError() documentation).

#define     USER_ERRORS         ((ECS_ERROR << 30) | BIT29)

#if !defined(__enumAdept104_ERROR_CODES__DEFINED_)

enum        enumAdept104_ERROR_CODES
                    {
                        //  No error must be indicated by 0
                        A104EC_NO_ERROR                     = 0,

                        //  First 'real' error, hence USER_ERRORS
                        A104EC_INPUT_PARAMETER_NULL         = USER_ERRORS,
                        A104EC_INPUT_PARAMETER_WRONG_SIZE,
                        A104EC_INPUT_PARAMETER_OUT_OF_RANGE,

                        A104EC_OUTPUT_PARAMETER_ERROR,

                        A104EC_UNSUPPORTED_BYTES_PER_WORD,

                        A104EC_AVT_COMMAND_ERROR,

                        A104EC_EEPROM_AREA_ERROR,           /*  Not used    */

                        A104EC_NOT_SUPPORTED_BY_ADEPT104,   /*  Not used    */

                        A104EC_MISALIGNED_ADDRESS_ERROR,

                        A104EC_ECIF_INPUT_FIFO_FULL,
                        A104EC_ECIF_INPUT_FIFO_WRITE_ERROR,
                        A104EC_ILLEGAL_ECIF_COMPONENT_SET_ID,
                        A104EC_NO_ECIF_COMPONENTS_SPECIFIED,

                        A104EC_FUNCTION_NOT_IN_BUILD,
                        A104EC_RESOURCE_NOT_CONFIGURED,
                    };

#define     __enumAdept104_ERROR_CODES__DEFINED_

#endif  //  #if !defined(__enumAdept104_ERROR_CODES__DEFINED_)

////////////////////////////////////////////////////////////////////////////

#endif  //  #if !defined(__A104_ErrorCodes_h__INCLUDED_)

////////////////////////////////////////////////////////////////////////////
