/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread */

#ifndef _Included_edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread
#define _Included_edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread_MIN_PRIORITY
#define edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread_MIN_PRIORITY 1L
#undef edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread_NORM_PRIORITY
#define edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread_NORM_PRIORITY 5L
#undef edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread_MAX_PRIORITY
#define edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread_MAX_PRIORITY 10L
/*
 * Class:     edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread
 * Method:    imageProcessingThreadProc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_jhuapl_nstd_swarm_WACSAgent_00024ImageProcessingThread_imageProcessingThreadProc
  (JNIEnv *, jobject);

/*
 * Class:     edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread
 * Method:    setParameter
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_edu_jhuapl_nstd_swarm_WACSAgent_00024ImageProcessingThread_setParameter
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     edu_jhuapl_nstd_swarm_WACSAgent_ImageProcessingThread
 * Method:    initialize
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_edu_jhuapl_nstd_swarm_WACSAgent_00024ImageProcessingThread_initialize
//  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
