/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.jhuapl.nstd.swarm.display.docking;

import com.javadocking.drag.DragListener;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.Action;

/**
 *
 * @author humphjc1
 */
public class DraggableTitleOverlayPanel extends DraggableJPanel
{
    TitleOverlayBar m_TitleBar;
    Component m_MainSubPanel;
    
    /**
     * Creates new form DraggableTitleOverlayPanel
     */
    public DraggableTitleOverlayPanel() 
    {
        initComponents();
        
        m_TitleBar = new TitleOverlayBar();
        jPanel2.setLayout(new GridLayout(1, 1));
        jPanel2.add(m_TitleBar);
    }
    
    public void addCloseAction (Action action)
    {
        m_TitleBar.addCloseAction (action);
    }
    
    public void addPanel (String title, final Component panel)
    {
        m_TitleBar.setText(title);
        m_MainSubPanel = panel;
        
        jPanel1.setLayout(new GridLayout(1, 1));
        jPanel1.add (m_MainSubPanel);
        
    }
    
    @Override
    public void addDragListener(DragListener dl) 
    {
        addMouseListener(dl);
        addMouseMotionListener(dl);
        
        jPanel1.addMouseListener(dl);
        jPanel1.addMouseMotionListener(dl);
        if (m_MainSubPanel != null)
        {
            m_MainSubPanel.addMouseListener(dl);
            m_MainSubPanel.addMouseMotionListener(dl);
        }
            
        jPanel2.addMouseListener(dl);
        jPanel2.addMouseMotionListener(dl);
        if (m_TitleBar != null)
        {
            m_TitleBar.addMouseListener(dl);
            m_TitleBar.addMouseMotionListener(dl);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
