/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.jhuapl.nstd.swarm.display.docking;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Action;
import javax.swing.ImageIcon;

/**
 *
 * @author humphjc1
 */
public class TitleOverlayBar extends DraggableJPanel
{
    private final static ImageIcon m_CloseBoxRedDefault_Icon = new javax.swing.ImageIcon(TitleOverlayBar.class.getResource("/icons/CloseBoxRed_Default.png"));
    private final static ImageIcon m_CloseBoxRedHighlight_Icon = new javax.swing.ImageIcon(TitleOverlayBar.class.getResource("/icons/CloseBoxRed_Highlight.png"));
    private final static ImageIcon m_CloseBoxRedPressed_Icon = new javax.swing.ImageIcon(TitleOverlayBar.class.getResource("/icons/CloseBoxRed_Pressed.png"));
    
    Action m_CloseAction;

    public TitleOverlayBar ()
    {
        this (false);
        jButton1.setIcon (m_CloseBoxRedDefault_Icon);
    }
    
    /**
     * Creates new form TitleOverlayBar
     */
    public TitleOverlayBar(boolean hideCloseBox) 
    {
        initComponents();
        
        jButton1.setVisible(!hideCloseBox);
        
        jButton1.addMouseListener(new MouseListener() 
        {
            private boolean m_Pressed = false;
            private boolean m_Entered = false;
            
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) 
            {
                m_Pressed = true;
                jButton1.setIcon (m_CloseBoxRedPressed_Icon);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
                jButton1.setIcon (m_CloseBoxRedDefault_Icon);
                m_Pressed = false;
                if (m_Entered && m_CloseAction != null)
                        m_CloseAction.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "Close"));
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                m_Entered = true;
                if (m_Pressed)
                    jButton1.setIcon (m_CloseBoxRedPressed_Icon);
                else
                    jButton1.setIcon (m_CloseBoxRedHighlight_Icon);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                m_Entered = false;
                jButton1.setIcon (m_CloseBoxRedDefault_Icon);
            }
        });
    }
    
    public void addCloseAction (Action action)
    {
        m_CloseAction = action;
    }
    
    public void setText (String title)
    {
        jLabel1.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(3000, 16));
        setMinimumSize(new java.awt.Dimension(10, 16));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);

        jButton1.setFocusable(false);
        jButton1.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
