/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_jhuapl_nstd_cbrnPods_bladewerxProcessor */

#ifndef _Included_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
#define _Included_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeInitialize
  (JNIEnv *, jobject);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeReset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeReset
  (JNIEnv *, jobject);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeResetPeaks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeResetPeaks
  (JNIEnv *, jobject);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeFitSpectrum
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeFitSpectrum
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeGetSpectrum
 * Signature: ([F[I)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeGetSpectrum
  (JNIEnv *, jobject, jfloatArray, jintArray);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeGetFittedSpectrum
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeGetFittedSpectrum
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeGetFitParameters
 * Signature: (S[F[F[F)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeGetFitParameters
  (JNIEnv *, jobject, jshort, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeGetFitResults
 * Signature: ([F[I)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeGetFitResults
  (JNIEnv *, jobject, jfloatArray, jintArray);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeGetPeakChannel
 * Signature: (S[S)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeGetPeakChannel
  (JNIEnv *, jobject, jshort, jshortArray);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativePutPeakChannel
 * Signature: (SS)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativePutPeakChannel
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeGetReferencePeak
 * Signature: (S[Z)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeGetReferencePeak
  (JNIEnv *, jobject, jshort, jbooleanArray);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativePutReferencePeak
 * Signature: (SZ)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativePutReferencePeak
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     edu_jhuapl_nstd_cbrnPods_bladewerxProcessor
 * Method:    nativeRawSpectrum
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_edu_jhuapl_nstd_cbrnPods_bladewerxProcessor_nativeRawSpectrum
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
